- name: install and start nginx
  hosts: dynamic_frontend
  become: yes #sudo access
  tasks:
  - name: install the nginx
    ansible.builtin.package:
      name: nginx
      state: installed
  - name: start the nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
