- name: shell vs command module
  hosts: local
  connection: local
  tasks:
   - name: redirecting ls output to file
     #ansible.builtin.command: ls -ltr > /tmp/output.txt
     ansible.builtin.shell: ls -ltr > /tmp/output.txt
     register: command_result
   - name: print output
     ansible.builtin.debug:
      msg: "{{ command_result }}"