- name: giving vars by prompt
  hosts: local
  connection: local
  vars_prompt:
   - name: USERNAME
     prompt: enter your username
     private: false
   - name: PASSWORD
     prompt: enter your password
     private: true
  tasks:
   - name: print course information
     ansible.builtin.debug:
      msg: "hello,my username is {{ USERNAME }}, my password is {{ PASSWORD }}"
        
