- name: giving vars by prompt
  hosts: frontend
  tasks:
   - name: print course information
     ansible.builtin.debug:
      msg: "hello, my course is {{ COURSE }}, duration is {{ DURATION }}, Trainer is {{ TRAINER }}"
        